from datetime import date
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class EventCategory(str, Enum):
    MACRO = "macro"
    INDUSTRY = "industry"
    SOCIAL = "social"
    PERSONAL = "personal"
    ENDOGENOUS = "endogenous"


class FutureEvent(BaseModel):
    """Candidate future event generated by the planner."""

    event_id: str
    title: str
    description: str
    category: EventCategory
    rationale: str
    source: Optional[str] = None
    estimated_window_start: date
    estimated_window_end: date
    relevance_to_profile: str
    uncertainty: float = Field(ge=0.0, le=1.0)
    expected_impact: float = Field(ge=0.0, le=1.0)
    affected_agents: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
