from unittest.mock import AsyncMock, patch

import pytest

from app.models import AgedPortrait, Checkpoint, Profile
from app.services.orchestrator import _fan_out_portraits


def _profile() -> Profile:
    return Profile(
        name="Sam", age=32, occupation="lawyer", workHours=80,
        topGoal="x", topFear="y", targetYear=2046, presentYear=2026,
    )


def _cps() -> list[Checkpoint]:
    return [
        Checkpoint(year=y, age=32 + (y - 2026), title="t", event="e", did="d", consequence="c")
        for y in (2028, 2031, 2034, 2038, 2042, 2046)
    ]


@pytest.mark.asyncio
async def test_fan_out_portraits_emits_one_event_per_non_hero_anchor() -> None:
    """fan_out_portraits emits 9 portrait events (4 high + 5 low) — one per
    (trajectory, index) EXCEPT the hero (high, last index) which the caller
    generates synchronously before phase: "complete" so it's already in the
    SimulationData payload."""
    async def fake_gen(*, target_age, target_year, trajectory, **_kwargs):
        return AgedPortrait(
            age=target_age, year=target_year, trajectory=trajectory,
            imageUrl=f"data:image/png;base64,FAKE-{trajectory}-{target_age}",
        )

    high = _cps()
    low = _cps()

    with patch("app.services.orchestrator.generate_aged_portrait", new=AsyncMock(side_effect=fake_gen)):
        events = []
        async for ev in _fan_out_portraits(
            profile=_profile(), selfie_bytes=b"x", selfie_mime="image/jpeg",
            high=high, low=low, ages=[32, 37, 42, 47, 52],
        ):
            events.append(ev)

    portrait_events = [e for e in events if e["phase"] == "portrait"]
    assert len(portrait_events) == 9
    high_events = [e for e in portrait_events if e["trajectory"] == "high"]
    low_events = [e for e in portrait_events if e["trajectory"] == "low"]
    assert len(high_events) == 4  # hero (index 4) excluded
    assert len(low_events) == 5
    assert {e["index"] for e in high_events} == {0, 1, 2, 3}


@pytest.mark.asyncio
async def test_fan_out_portraits_emits_portrait_error_on_null_url() -> None:
    async def fake_gen(*, target_age, target_year, trajectory, **_kwargs):
        return AgedPortrait(age=target_age, year=target_year, trajectory=trajectory, imageUrl=None)

    with patch("app.services.orchestrator.generate_aged_portrait", new=AsyncMock(side_effect=fake_gen)):
        events = []
        async for ev in _fan_out_portraits(
            profile=_profile(), selfie_bytes=b"x", selfie_mime="image/jpeg",
            high=_cps(), low=_cps(), ages=[32, 37, 42, 47, 52],
        ):
            events.append(ev)

    # 9 attempted (hero is generated outside the fan-out) — all fail -> 9 errors.
    error_events = [e for e in events if e["phase"] == "portrait_error"]
    assert len(error_events) == 9


from app.services.orchestrator import _fan_out_portraits_branched


@pytest.mark.asyncio
async def test_branched_portrait_fanout_preserves_pre_intervention_high() -> None:
    """High portraits with year < intervention.year are re-emitted verbatim
    from the original simulation; high portraits at/after the intervention
    year are regenerated; all 5 low portraits are regenerated."""
    profile = _profile()
    ages = [32, 37, 42, 47, 52]
    span = profile.targetYear - profile.presentYear  # 20

    original_high = [
        AgedPortrait(
            age=a, year=profile.presentYear + round(span * (i / 4)),
            trajectory="high", imageUrl=f"data:image/png;base64,ORIGINAL-{i}",
        )
        for i, a in enumerate(ages)
    ]

    intervention = {"year": 2036, "text": "I quit"}  # cuts at index 2 (age 42)

    async def fake_gen(*, target_age, target_year, trajectory, **_kwargs):
        return AgedPortrait(
            age=target_age, year=target_year, trajectory=trajectory,
            imageUrl=f"data:image/png;base64,REGEN-{trajectory}-{target_age}",
        )

    with patch("app.services.orchestrator.generate_aged_portrait", new=AsyncMock(side_effect=fake_gen)):
        events = []
        async for ev in _fan_out_portraits_branched(
            profile=profile, selfie_bytes=b"x", selfie_mime="image/jpeg",
            high=_cps(), low=_cps(), ages=ages,
            intervention=intervention,
            original_portraits=original_high,
        ):
            events.append(ev)

    high_events = [e for e in events if e["phase"] == "portrait" and e["trajectory"] == "high"]
    low_events = [e for e in events if e["phase"] == "portrait" and e["trajectory"] == "low"]
    # Hero (index 4) is now generated by the caller before phase: "complete",
    # so the branched fan-out emits 4 high (0,1,2,3) + 5 low.
    assert len(high_events) == 4
    assert len(low_events) == 5
    # Indices 0 and 1 (years 2026, 2031) are pre-intervention -> preserved.
    preserved = [e for e in high_events if e["index"] in (0, 1)]
    assert all("ORIGINAL" in e["portrait"]["imageUrl"] for e in preserved)
    # Indices 2 and 3 are at/after intervention.year -> regenerated.
    regen = [e for e in high_events if e["index"] in (2, 3)]
    assert all("REGEN" in e["portrait"]["imageUrl"] for e in regen)
